<?php

namespace WG\ProjectBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository {
    
    public function search($string, $limit){
        $query = $this->getEntityManager()->createQuery(
                'SELECT t FROM WGProjectBundle:Tag t
                 WHERE t.titleLower LIKE :search');
        $query->setMaxResults($limit);
        $query->setParameter('search', strtolower($string)."%");
        return $query->getResult();
    }
}
