parameters:
#    wg_project.example.class: WG\ProjectBundle\Example

services:
#    wg_project.example:
#        class: %wg_project.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
